tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'caskroom/cask'

brew 'ansible'
brew 'ctags'
brew 'docker'
brew 'git'
brew 'go'
brew 'gource'
brew 'imagemagick'
brew 'nvm'
brew 'python'
brew 'python@2'
brew 'vim'
brew 'zsh'

cask 'google-cloud-sdk'
cask 'macvim'
cask 'sublime-merge'
cask 'sublime-text'
